### ISSUE TITLE
[質問] サポートは終わりましたか？

### ISSUE THREAD

**Issue by shinriyo** [EsriJapan/startup-swift-ios#1]
新しいバージョンのサンプルはありますか？
SDK自体サポートは今後しないでしょうか？

**Comment by yozaw** [comment]
ご連絡ありがとうございます。
こちらのリポジトリで使用しているSDKのバージョンはサポート終了しているため、下記のガイドをご覧いただければと思います。最新バージョンでは、SwiftUIの対応などSwiftファーストのSDKとして更新されています。

スタートアップガイド
https://esrijapan.github.io/arcgis-dev-resources/guide/create-app/create-startup-app-ios/

インストールガイド
https://esrijapan.github.io/arcgis-dev-resources/tips/ios/install-ios-200.x/

サンプルコード
https://developers.arcgis.com/swift/sample-code/
